- name: "Vagrant specific configuration"
  hosts: all
  tasks:
    - name: "Ensure /etc/hosts is distributed"
      template: src=templates/hosts.j2 dest=/etc/hosts backup=yes
    - name: "Ensure the firewall is disabled"
      service: name="firewalld" state="stopped" enabled="no"
