- name: "Ensure Kong is installed and configured"
  hosts: all
  tasks:
    - name: "Ensure repository for Cassandra is present"
      copy: src="files/cassandra.repo"
            dest="/etc/yum.repos.d/cassandra.repo"
            mode=444 owner=root group=root
      notify:
        - "Update the yum cache"

    - name: "Ensure Cassandra is installed with dependencies"
      yum: name="{{ item }}" state="installed"
      with_items:
        - "dsc21"
        - "java-1.8.0-openjdk"

    - name: "Ensure Cassandra is configured"
      copy: src="files/cassandra.yaml"
            dest="/etc/cassandra/default.conf/cassandra.yaml"
            mode=444 owner=root group=root
      notify:
        - "Restart Cassandra"

    - name: "Ensure Cassandra is running"
      service: name="cassandra" state="running" enabled="yes"

    # Download Kong
    # Install Kong
    # Configure Kong
    # Start Kong 

  handlers:
    - name: "Update the yum cache"
      command: "yum clean metadata"

    - name: "Restart Cassandra"
      service: name="cassandra" state="restarted"
