test:
  hostport: httpbin.org:80
#  hostport: localhost:5000
  uri: http://${test.hostport}
server:
  port: 8000
spring:
  cloud:
    gateway:
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      # =====================================
      - id: default_path_to_httpbin
        uri: ${test.uri}
        order: 10000
        predicates:
        - Path=/**
  main.web-application-type: reactive
logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.http.server.reactive: WARN
    org.springframework.web.reactive: WARN
    reactor.ipc.netty: WARN