- name: "Setup Boom"
  hosts: all
  environment:
    GOPATH: "/usr/local/go"
  tasks:
    - name: "Install disabled Centos-Base repo for RHEL7"
      copy: src="files/centos7-base.repo" dest="/etc/yum.repos.d/centos7-base.repo" mode="0444"
      when: ansible_distribution in ['RedHat'] and
            ansible_distribution_major_version in ['7']

    - name: "Install golang with Centos repo for RHEL7"
      yum: name="golang" enablerepo="centos7-base" state="installed"
      when: ansible_distribution in ['RedHat'] and
            ansible_distribution_major_version in ['7']

    - name: "Ensure tools are installed"
      yum: name="{{ item }}" state="installed"
      with_items:
        - "git"
        - "golang"

    - name: "Create directory structure"
      file: path="{{ item }}" state="directory" mode="0755"
      with_items:
        - "/usr/local/go"
        - "/usr/local/go/src"
        - "/usr/local/go/pkg"
        - "/usr/local/go/bin"

    - name: "Download and install Dummy-API"
      command: "/bin/go get github.com/espebra/boom"
      args:
        creates: "/usr/local/go/src/github.com/espebra/boom/"

    - name: "Ensure that test wrappers are present"
      copy: src="files/tests/" dest="/usr/local/bin/" mode="0555"
